# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGEZukDrf7H1MLLpU34JwPIOWLmeDAGy
"""

import torch
import torch.nn as nn

import open_clip

#Load CLIP
clip_model, _, preprocess = open_clip.create_model_and_transforms(
    'ViT-B-32',
    pretrained='openai'
)

#Freeze CLIP
for param in clip_model.parameters():
    param.requires_grad = False

#Fakeimage Detector
class FakeDetector(nn.Module):
    def __init__(self, clip_model):
        super().__init__()
        self.clip_model = clip_model
        self.head = nn.Linear(512, 1)
    def forward(self, images):
        with torch.no_grad():
            features = self.clip_model.encode_image(images)
        return self.head(features).squeeze(-1)

# Function that takes in a folder containing images and output fake probability for each image
import json
import glob

def run_inference(image_dir, output_path, model):

    results = []

    for path in glob.glob(f"{image_dir}/*"):

        img = Image.open(path).convert("RGB")

        transformed = preprocess(img).unsqueeze(0).cuda()

        pred = torch.sigmoid(model(transformed)).item()

        results.append({
            "image_path": path,
            "pred": pred})

    with open(output_path, "w") as f:
        json.dump(results, f, indent=2)


from torch.utils.data import Dataset
from PIL import Image

class ImageDataset(Dataset):
    def __init__(self, image_paths, labels, transform=None):
        self.image_paths = image_paths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img = Image.open(self.image_paths[idx]).convert("RGB")
        if self.transform:
            img = self.transform(img)
        return img, self.labels[idx]

import os; print(os.getcwd())

from torch.utils.data import DataLoader
import sys
sys.path.append('/content/Centaurus/aigc-detection3')


import json
with open('/content/Centaurus/aigc-detection3/train_splits.json') as f:
    data = json.load(f)
    train_paths = data["train_paths"]
    train_labels = data["train_labels"]
model = FakeDetector(clip_model).cuda()

train_paths = [p.replace("\\", "/") for p in train_paths]

import sys; sys.modules.pop('data.dataset', None); sys.modules.pop('data', None)
train_dataset = ImageDataset(train_paths, train_labels, transform=preprocess)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

#need to download the kaggle dataset on your laptop
import zipfile

with zipfile.ZipFile('/content/archive.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/data/cifake')



for images, labels in train_loader:
  print(model(images.cuda()));
  break

optimizer = torch.optim.Adam(model.head.parameters(), lr=1e-4)
loss_fn = nn.BCEWithLogitsLoss()
for epoch in range(5):
    for images, labels in train_loader:
        images, labels = images.cuda(), labels.float().cuda()
        optimizer.zero_grad()
        preds = model(images)
        loss = loss_fn(preds, labels)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch}, loss: {loss.item()}")

model.eval()
run_inference('/content/data/cifake/train/REAL', '/content/test_output.json', model)

import json
print(json.load(open('/content/test_output.json'))[:3])



import sys
sys.path.append('/content/Centaurus')

from augmentations import get_train_augmentation

train_transform = get_train_augmentation()
from PIL import Image
import numpy as np

train_augmentation = get_train_augmentation()

# grab one real image to test on
test_img = Image.open('/content/data/cifake/train/REAL/2147 (2).jpg').convert("RGB")

# albumentations transforms expect a numpy array, not a PIL Image directly
result = train_transform(image=np.array(test_img))
print(result['image'].shape)  # confirms it ran and produced a tensor/array with the expected shape
