# -*- coding: utf-8 -*-
# """train.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1dGEZukDrf7H1MLLpU34JwPIOWLmeDAGy
# """
# # NOTE: Exported from Colab. Contains personal Google Drive paths
# # (/content/drive/MyDrive/...) specific to the author's environment —
# # adjust these paths if running in your own Colab session.

# import torch
# import torch.nn as nn
# !pip install open_clip_torch
# import open_clip

# #Load CLIP
# clip_model, _, preprocess = open_clip.create_model_and_transforms(
#     'ViT-B-32',
#     pretrained='openai'
# )

# #Freeze CLIP
# for param in clip_model.parameters():
#     param.requires_grad = False

# #Fakeimage Detector
# class FakeDetector(nn.Module):
#     def __init__(self, clip_model):
#         super().__init__()
#         self.clip_model = clip_model
#         self.head = nn.Linear(512, 1)
#     def forward(self, images):
#         with torch.no_grad():
#             features = self.clip_model.encode_image(images)
#         return self.head(features).squeeze(-1)

# # Function that takes in a folder containing images and output fake probability for each image
# import json
# import glob

# def run_inference(image_dir, output_path, model):

#     results = []

#     for path in glob.glob(f"{image_dir}/*"):

#         img = Image.open(path).convert("RGB")

#         transformed = preprocess(img).unsqueeze(0).cuda()

#         pred = torch.sigmoid(model(transformed)).item()

#         results.append({
#             "image_path": path,
#             "pred": pred})

#     with open(output_path, "w") as f:
#         json.dump(results, f, indent=2)

# #To transfer over files from Centaurus
# !git clone https://github.com/pranathichijs-ai/Centaurus.git
# !ls

# #ImageDataset is function
# from torch.utils.data import Dataset, DataLoader
# from PIL import Image

# class ImageDataset(Dataset):
#     def __init__(self, image_paths, labels, transform=None):
#         self.image_paths = image_paths
#         self.labels = labels
#         self.transform = transform

#     def __len__(self):
#         return len(self.image_paths)

#     def __getitem__(self, idx):
#         img = Image.open(self.image_paths[idx]).convert("RGB")
#         if self.transform:
#             img = self.transform(img)
#         return img, self.labels[idx]

# #build train_loader
# #from A's CIFAKE-only split, sanity check the model runs
# with open('/content/Centaurus/aigc-detection3/data/train_splits.json') as f:
#     data = json.load(f)
#     train_paths = data["train_paths"]
#     train_labels = data["train_labels"]

# train_paths = [p.replace("\\", "/") for p in train_paths]  # Windows path fix (harmless if already fixed at source)

# model = FakeDetector(clip_model).cuda()

# train_dataset = ImageDataset(train_paths, train_labels, transform=preprocess)
# train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# #need to download the kaggle dataset on your laptop
# # Make sure the CIFAKE zip is extracted before this will find images —
# #this step is for direct upload from kaggle onto laptop
# import zipfile
# with zipfile.ZipFile('/content/archive.zip', 'r') as zip_ref:
#     zip_ref.extractall('/content/data/cifake')

# !ls /content/data/cifake/train/

# #run aome images through FakeDetector model
# # quick check — should print a batch of raw model outputs with no errors
# for images, labels in train_loader:
#     print(model(images.cuda()))
#     break

# from google.colab import drive
# drive.mount('/content/drive')

# import shutil
# shutil.copy('/content/drive/MyDrive/cifake_sidset.zip', '/content/cifake_sidset.zip')

# import zipfile
# with zipfile.ZipFile('/content/cifake_sidset.zip', 'r') as zip_ref:
#     zip_ref.extractall('/content/data')

# #optimizer to adjusts your classifier's numbers based on how wrong its guesses were
# #first training loop
# optimizer = torch.optim.Adam(model.head.parameters(), lr=1e-4)
# loss_fn = nn.BCEWithLogitsLoss()

# for epoch in range(5):
#     for images, labels in train_loader:
#         images, labels = images.cuda(), labels.float().cuda()
#         optimizer.zero_grad()
#         preds = model(images)
#         loss = loss_fn(preds, labels)
#         loss.backward()
#         optimizer.step()
#     print(f"Epoch {epoch}, loss: {loss.item()}")

# #rerun run_inference on some new sample images.this is to confirm is works
# model.eval()
# run_inference('/content/data/cifake/train/REAL', '/content/test_output.json', model)

# import json
# print(json.load(open('/content/test_output.json'))[:3])

# #turning above training code into reusable function
# def train_model(train_loader, epochs=5):
#     for epoch in range(epochs):
#         for images, labels in train_loader:
#             images, labels = images.cuda(), labels.float().cuda()
#             optimizer.zero_grad()
#             preds = model(images)
#             loss = loss_fn(preds, labels)
#             loss.backward()
#             optimizer.step()
#         print(f"Epoch {epoch}, loss: {loss.item()}")
#     return model

# !cd /content/Centaurus && git pull

# print(f"Loaded {len(train_paths)} training images")

# import os
# print(os.path.exists(train_paths[0]))
# print(os.path.exists([p for p in train_paths if 'sid_set' in p][0]))

# #Build a new DataLoader using A's combined dataset
# # Step 1: load A's NEW combined paths/labels
# with open('/content/Centaurus/aigc-detection3/data/train_splits.json') as f:
#     data = json.load(f)
#     train_paths = data["train_paths"]
#     train_labels = data["train_labels"]

# train_paths = [p.replace("\\", "/") for p in train_paths]  # backslash fix, still needed

# # Step 2: build the new DataLoader from the combined data
# train_dataset = ImageDataset(train_paths, train_labels, transform=preprocess)
# train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# # Step 3: train
# model = train_model(train_loader)

# #save once training cell above completes successfully (for a's dataset)
# torch.save(model.state_dict(), "model_plain.pt")

# #ensure the albumentation ver is the same for C
# !pip install albumentations==1.3.1

# #rebuild ImageDataset passing C'strain_augmentation pipeline in as the transform argument
# import sys
# sys.path.append('/content/Centaurus')
# from augmentations import get_train_augmentation
# import numpy as np

# train_transform = get_train_augmentation()

# # Wrap C's albumentations pipeline so it matches what ImageDataset expects
# def augment_transform(img):
#     return train_transform(image=np.array(img))['image']

# # Rebuild the dataset using the SAME train_paths/train_labels as before,
# # just with the augmentation transform instead of preprocess
# train_dataset = ImageDataset(train_paths, train_labels, transform=augment_transform)
# train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# # Train the second (augmented) model
# model = train_model(train_loader)

# #saving the training using C's pipeline
# torch.save(model.state_dict(), "model_augmented.pt")

# import os
# print(os.path.exists("model_augmented.pt"))
# print(os.path.getsize("model_augmented.pt"))  # should be some sizable number of bytes, not 0

# import shutil
# shutil.copy('model_augmented.pt', '/content/drive/MyDrive/Centaurus/model_augmented.pt')

# import os
# print(os.path.exists('model_augmented.pt'))

# import os
# os.makedirs('/content/drive/MyDrive/Centaurus', exist_ok=True)

# import shutil
# shutil.copy('model_augmented.pt', '/content/drive/MyDrive/Centaurus/model_augmented.pt')

# #locating val_paths and val_labels
# with open('/content/Centaurus/aigc-detection3/data/val_splits.json') as f:
#     val_data = json.load(f)
#     val_paths = val_data["val_paths"]
#     val_labels = val_data["val_labels"]

# val_paths = [p.replace("\\", "/") for p in val_paths]  # same backslash fix as train_paths

# #error analysis code
# import sys
# sys.path.append('/content/Centaurus')
# from scoring import score_from_files, get_misclassified
# import json
# from PIL import Image
# import numpy as np # Needed for np.isnan


# # Step 1: run inference on your VALIDATION set (images with known true labels,
# # not train_loader — you want images the model didn't train on)
# model.eval()

# # Original `run_inference` function is not suitable as val_paths are not under a single directory.
# # Performing inference directly on val_paths.
# predictions = []
# for path in val_paths:
#     try:
#         # Assuming val_paths are relative to /content/
#         img = Image.open(path).convert("RGB")
#         transformed = preprocess(img).unsqueeze(0).cuda()
#         pred = torch.sigmoid(model(transformed)).item()
#         predictions.append({
#             "image_path": path,
#             "pred": pred
#         })
#     except FileNotFoundError:
#         print(f"Warning: Image not found at {path}. Skipping.")
#     except Exception as e:
#         print(f"Error processing image {path}: {e}. Skipping.")

# with open('/content/val_predictions.json', 'w') as f:
#     json.dump(predictions, f, indent=2)

# # ^ adjust this path to wherever your actual validation images live

# # Step 2: build a labels.json mapping image_path -> true label,
# # matching val_paths/val_labels you already have in memory
# # Ensure labels_dict uses the same paths as predictions (which are from val_paths)
# labels_dict = {path: label for path, label in zip(val_paths, val_labels)}
# with open('/content/val_labels.json', 'w') as f:
#     json.dump(labels_dict, f)

# # Step 3: score everything — this returns accuracy/precision/recall/f1/auc
# # PLUS per-image records needed for error analysis
# metrics = score_from_files('/content/val_predictions.json', '/content/val_labels.json')

# # Handle potential None or NaN values gracefully for printing
# accuracy_str = f"{metrics['accuracy']:.3f}" if not np.isnan(metrics['accuracy']) else "N/A"
# auc_str = f"{metrics['auc']:.3f}" if metrics['auc'] is not None else "N/A"

# print(f"Accuracy: {accuracy_str}, AUC: {auc_str}")

# # Step 4: pull the most confidently-wrong examples of each kind
# false_positives = get_misclassified(metrics, kind="false_positive", top_n=3)  # real flagged as AI
# false_negatives = get_misclassified(metrics, kind="false_negative", top_n=3)  # AI flagged as real

# print("Most confident false positives (real images called fake):")
# for r in false_positives:
#     print(r)

# print("\nMost confident false negatives (fake images called real):")
# for r in false_negatives:
#     print(r)

# #print error analysis
# import json

# results = {
#     "false_positives": false_positives,
#     "false_negatives": false_negatives
# }

# with open('/content/misclassified_examples.json', 'w') as f:
#     json.dump(results, f, indent=2)

# from google.colab import files
# files.download('/content/misclassified_examples.json')

# print(model)  # does this error, or does it print the model architecture?

# #rereunning inference script on a cifake test REAL (untested images)
# model.eval()
# run_inference('/content/data/cifake/test/REAL', '/content/final_check_output.json', model)
# # swap in whichever fresh folder you actually found

# import json
# print(json.load(open('/content/final_check_output.json'))[:3])

# shutil.copy('/content/drive/MyDrive/Centaurus/model_augmented.pt', '/content/model_augmented.pt')

# model = FakeDetector(clip_model).cuda()
# model.load_state_dict(torch.load('model_augmented.pt'))
# model.eval()

# #locating val_paths and val_labels
# with open('/content/Centaurus/aigc-detection3/data/val_splits.json') as f:
#     val_data = json.load(f)
#     val_paths = val_data["val_paths"]
#     val_labels = val_data["val_labels"]

# val_paths = [p.replace("\\", "/") for p in val_paths]  # same backslash fix as train_paths

# #error analysis code
# import sys
# sys.path.append('/content/Centaurus')
# from scoring import score_from_files, get_misclassified
# import json
# from PIL import Image
# import numpy as np # Needed for np.isnan


# # Step 1: run inference on your VALIDATION set (images with known true labels,
# # not train_loader — you want images the model didn't train on)
# model.eval()

# # Original `run_inference` function is not suitable as val_paths are not under a single directory.
# # Performing inference directly on val_paths.
# predictions = []
# for path in val_paths:
#     try:
#         # Assuming val_paths are relative to /content/
#         img = Image.open(path).convert("RGB")
#         transformed = preprocess(img).unsqueeze(0).cuda()
#         pred = torch.sigmoid(model(transformed)).item()
#         predictions.append({
#             "image_path": path,
#             "pred": pred
#         })
#     except FileNotFoundError:
#         print(f"Warning: Image not found at {path}. Skipping.")
#     except Exception as e:
#         print(f"Error processing image {path}: {e}. Skipping.")

# with open('/content/val_predictions.json', 'w') as f:
#     json.dump(predictions, f, indent=2)

# # ^ adjust this path to wherever your actual validation images live

# # Step 2: build a labels.json mapping image_path -> true label,
# # matching val_paths/val_labels you already have in memory
# # Ensure labels_dict uses the same paths as predictions (which are from val_paths)
# labels_dict = {path: label for path, label in zip(val_paths, val_labels)}
# with open('/content/val_labels.json', 'w') as f:
#     json.dump(labels_dict, f)

# # Step 3: score everything — this returns accuracy/precision/recall/f1/auc
# # PLUS per-image records needed for error analysis
# metrics = score_from_files('/content/val_predictions.json', '/content/val_labels.json')

# # Handle potential None or NaN values gracefully for printing
# accuracy_str = f"{metrics['accuracy']:.3f}" if not np.isnan(metrics['accuracy']) else "N/A"
# auc_str = f"{metrics['auc']:.3f}" if metrics['auc'] is not None else "N/A"

# print(f"Accuracy: {accuracy_str}, AUC: {auc_str}")

# # Step 4: pull the most confidently-wrong examples of each kind
# false_positives = get_misclassified(metrics, kind="false_positive", top_n=3)  # real flagged as AI
# false_negatives = get_misclassified(metrics, kind="false_negative", top_n=3)  # AI flagged as real

# print("Most confident false positives (real images called fake):")
# for r in false_positives:
#     print(r)

# print("\nMost confident false negatives (fake images called real):")
# for r in false_negatives:
#     print(r)

# import json

# error_analysis_output = {
#     "accuracy": accuracy_str,
#     "auc": auc_str,
#     "false_positives": false_positives,
#     "false_negatives": false_negatives
# }

# with open('/content/error_analysis_final.json', 'w') as f:
#     json.dump(error_analysis_output, f, indent=2)

# from google.colab import files
# files.download('/content/error_analysis_final.json')

# import json

# results = {
#     "false_positives": false_positives,
#     "false_negatives": false_negatives
# }

# with open('/content/misclassified_examples.json', 'w') as f:
#     json.dump(results, f, indent=2)

# from google.colab import files
# files.download('/content/misclassified_examples.json')

# from google.colab import drive
# drive.mount('/content/drive')
# model.load_state_dict(torch.load("/content/drive/MyDrive/model_plain.pt"))

# import albumentations as A
# from albumentations.pytorch import ToTensorV2

# test_conditions = {
#     "Clean": A.Compose([
#         A.Resize(224, 224),
#         A.Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711)),
#         ToTensorV2()
#     ]),

#     "JPEG q30": A.Compose([
#         A.Resize(224, 224),
#         A.ImageCompression(quality_lower=30, quality_upper=30, p=1.0),
#         A.Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711)),
#         ToTensorV2()
#     ]),

#     "Blur σ=2": A.Compose([
#         A.Resize(224, 224),
#         A.GaussianBlur(sigma_limit=(2.0, 2.0), p=1.0),
#         A.Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711)),
#         ToTensorV2()
#     ]),

#     "Crop 80%": A.Compose([
#         A.Resize(224, 224),
#         A.RandomResizedCrop(height=224, width=224, scale=(0.8, 0.8), p=1.0),
#         A.Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711)),
#         ToTensorV2()
#     ]),
# }

# import os
# os.listdir('/content/Centaurus/aigc-detection3/eval')

# import shutil
# shutil.copy('/content/Centaurus/scoring.py', '/content/Centaurus/aigc-detection3/eval/scoring.py')

# import sys
# sys.path.append('/content/Centaurus/aigc-detection3')
# from eval.evaluate import evaluate

# import numpy as np

# def wrap_transform(transform):
#     def wrapped(img):
#         return transform(image=np.array(img))['image']
#     return wrapped

# test_conditions_wrapped = {name: wrap_transform(t) for name, t in test_conditions.items()}

# #run C's evaluate across 5 conditions
# #compare values with C
# model = FakeDetector(clip_model)
# model.load_state_dict(torch.load("/content/drive/MyDrive/model_plain.pt"))
# model = model.cuda().eval()

# results_plain = {}
# for name, transform in test_conditions_wrapped.items():
#     val_dataset = ImageDataset(val_paths, val_labels, transform=transform)
#     val_loader = DataLoader(val_dataset, batch_size=32)
#     acc, auc = evaluate(model, val_loader)
#     results_plain[name] = {"accuracy": round(acc*100, 2), "auc": round(auc, 4)}

# print(results_plain)

# #download results to compare with C's model_plain
# import json
# from google.colab import files

# with open('results_plain.json', 'w') as f:
#     json.dump(results_plain, f, indent=2)

# files.download('results_plain.json')

# #run C's evaluate across 5 conditions
# #compare values with C
# model = FakeDetector(clip_model)
# model.load_state_dict(torch.load("/content/drive/MyDrive/model_augmented.pt"))
# model = model.cuda().eval()

# results_augmented = {}
# for name, transform in test_conditions_wrapped.items():
#     val_dataset = ImageDataset(val_paths, val_labels, transform=transform)
#     val_loader = DataLoader(val_dataset, batch_size=32)
#     acc, auc = evaluate(model, val_loader)
#     results_augmented[name] = {"accuracy": round(acc*100, 2), "auc": round(auc, 4)}

# print(results_augmented)

# import json
# from google.colab import files

# combined = {"plain": results_plain, "augmented": results_augmented}

# with open('robustness_recheck.json', 'w') as f:
#     json.dump(combined, f, indent=2)

# files.download('robustness_recheck.json')

# !pip freeze > requirements.txt

# !wc -l requirements.txt

"""train.ipynb (FIXED)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGEZukDrf7H1MLLpU34JwPIOWLmeDAGy

FIXES APPLIED:
- All sys.path.append('/content/Centaurus') changed to
  sys.path.append('/content/Centaurus/aigc-detection3'), since that's
  where scoring.py, augmentations.py, and eval/ actually live.
- shutil.copy source path for scoring.py corrected to include the
  aigc-detection3 subfolder.
"""
# NOTE: Exported from Colab. Contains personal Google Drive paths
# (/content/drive/MyDrive/...) specific to the author's environment —
# adjust these paths if running in your own Colab session.

import torch
import torch.nn as nn
!pip install open_clip_torch
import open_clip

#Load CLIP
clip_model, _, preprocess = open_clip.create_model_and_transforms(
    'ViT-B-32',
    pretrained='openai'
)

#Freeze CLIP
for param in clip_model.parameters():
    param.requires_grad = False

#Fakeimage Detector
class FakeDetector(nn.Module):
    def __init__(self, clip_model):
        super().__init__()
        self.clip_model = clip_model
        self.head = nn.Linear(512, 1)
    def forward(self, images):
        with torch.no_grad():
            features = self.clip_model.encode_image(images)
        return self.head(features).squeeze(-1)

import json
import glob
from PIL import Image

def run_inference(image_dir, output_path, model):
    results = []
    for path in glob.glob(f"{image_dir}/*"):
        img = Image.open(path).convert("RGB")
        transformed = preprocess(img).unsqueeze(0).cuda()
        pred = torch.sigmoid(model(transformed)).item()
        results.append({"image_path": path, "pred": pred})
    with open(output_path, "w") as f:
        json.dump(results, f, indent=2)

#To transfer over files from Centaurus
!git clone https://github.com/pranathichijs-ai/Centaurus.git
!ls

from torch.utils.data import Dataset, DataLoader

class ImageDataset(Dataset):
    def __init__(self, image_paths, labels, transform=None):
        self.image_paths = image_paths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img = Image.open(self.image_paths[idx]).convert("RGB")
        if self.transform:
            img = self.transform(img)
        return img, self.labels[idx]

with open('/content/Centaurus/aigc-detection3/data/train_splits.json') as f:
    data = json.load(f)
    train_paths = data["train_paths"]
    train_labels = data["train_labels"]

train_paths = [p.replace("\\", "/") for p in train_paths]

model = FakeDetector(clip_model).cuda()

train_dataset = ImageDataset(train_paths, train_labels, transform=preprocess)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

import zipfile
with zipfile.ZipFile('/content/archive.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/data/cifake')

!ls /content/data/cifake/train/

for images, labels in train_loader:
    print(model(images.cuda()))
    break

from google.colab import drive
drive.mount('/content/drive')

import shutil
shutil.copy('/content/drive/MyDrive/cifake_sidset.zip', '/content/cifake_sidset.zip')

with zipfile.ZipFile('/content/cifake_sidset.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/data')

optimizer = torch.optim.Adam(model.head.parameters(), lr=1e-4)
loss_fn = nn.BCEWithLogitsLoss()

for epoch in range(5):
    for images, labels in train_loader:
        images, labels = images.cuda(), labels.float().cuda()
        optimizer.zero_grad()
        preds = model(images)
        loss = loss_fn(preds, labels)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch}, loss: {loss.item()}")

model.eval()
run_inference('/content/data/cifake/train/REAL', '/content/test_output.json', model)
print(json.load(open('/content/test_output.json'))[:3])

def train_model(train_loader, epochs=5):
    for epoch in range(epochs):
        for images, labels in train_loader:
            images, labels = images.cuda(), labels.float().cuda()
            optimizer.zero_grad()
            preds = model(images)
            loss = loss_fn(preds, labels)
            loss.backward()
            optimizer.step()
        print(f"Epoch {epoch}, loss: {loss.item()}")
    return model

!cd /content/Centaurus && git pull

print(f"Loaded {len(train_paths)} training images")

import os
print(os.path.exists(train_paths[0]))
print(os.path.exists([p for p in train_paths if 'sid_set' in p][0]))

with open('/content/Centaurus/aigc-detection3/data/train_splits.json') as f:
    data = json.load(f)
    train_paths = data["train_paths"]
    train_labels = data["train_labels"]

train_paths = [p.replace("\\", "/") for p in train_paths]

train_dataset = ImageDataset(train_paths, train_labels, transform=preprocess)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

model = train_model(train_loader)

torch.save(model.state_dict(), "model_plain.pt")

!pip install albumentations==1.3.1

import sys
sys.path.append('/content/Centaurus/aigc-detection3')   # FIXED: was '/content/Centaurus'
from augmentations import get_train_augmentation
import numpy as np

train_transform = get_train_augmentation()

def augment_transform(img):
    return train_transform(image=np.array(img))['image']

train_dataset = ImageDataset(train_paths, train_labels, transform=augment_transform)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

model = train_model(train_loader)

torch.save(model.state_dict(), "model_augmented.pt")

import os
print(os.path.exists("model_augmented.pt"))
print(os.path.getsize("model_augmented.pt"))

import shutil
shutil.copy('model_augmented.pt', '/content/drive/MyDrive/Centaurus/model_augmented.pt')

import os
print(os.path.exists('model_augmented.pt'))

os.makedirs('/content/drive/MyDrive/Centaurus', exist_ok=True)

shutil.copy('model_augmented.pt', '/content/drive/MyDrive/Centaurus/model_augmented.pt')

with open('/content/Centaurus/aigc-detection3/data/val_splits.json') as f:
    val_data = json.load(f)
    val_paths = val_data["val_paths"]
    val_labels = val_data["val_labels"]

val_paths = [p.replace("\\", "/") for p in val_paths]

import sys
sys.path.append('/content/Centaurus/aigc-detection3')   # FIXED: was '/content/Centaurus'
from scoring import score_from_files, get_misclassified
import json
import numpy as np

model.eval()

predictions = []
for path in val_paths:
    try:
        img = Image.open(path).convert("RGB")
        transformed = preprocess(img).unsqueeze(0).cuda()
        pred = torch.sigmoid(model(transformed)).item()
        predictions.append({"image_path": path, "pred": pred})
    except FileNotFoundError:
        print(f"Warning: Image not found at {path}. Skipping.")
    except Exception as e:
        print(f"Error processing image {path}: {e}. Skipping.")

with open('/content/val_predictions.json', 'w') as f:
    json.dump(predictions, f, indent=2)

labels_dict = {path: label for path, label in zip(val_paths, val_labels)}
with open('/content/val_labels.json', 'w') as f:
    json.dump(labels_dict, f)

metrics = score_from_files('/content/val_predictions.json', '/content/val_labels.json')

accuracy_str = f"{metrics['accuracy']:.3f}" if not np.isnan(metrics['accuracy']) else "N/A"
auc_str = f"{metrics['auc']:.3f}" if metrics['auc'] is not None else "N/A"

print(f"Accuracy: {accuracy_str}, AUC: {auc_str}")

false_positives = get_misclassified(metrics, kind="false_positive", top_n=3)
false_negatives = get_misclassified(metrics, kind="false_negative", top_n=3)

print("Most confident false positives (real images called fake):")
for r in false_positives:
    print(r)

print("\nMost confident false negatives (fake images called real):")
for r in false_negatives:
    print(r)

results = {"false_positives": false_positives, "false_negatives": false_negatives}
with open('/content/misclassified_examples.json', 'w') as f:
    json.dump(results, f, indent=2)

from google.colab import files
files.download('/content/misclassified_examples.json')

print(model)

model.eval()
run_inference('/content/data/cifake/test/REAL', '/content/final_check_output.json', model)
print(json.load(open('/content/final_check_output.json'))[:3])

shutil.copy('/content/drive/MyDrive/Centaurus/model_augmented.pt', '/content/model_augmented.pt')

model = FakeDetector(clip_model).cuda()
model.load_state_dict(torch.load('model_augmented.pt'))
model.eval()

with open('/content/Centaurus/aigc-detection3/data/val_splits.json') as f:
    val_data = json.load(f)
    val_paths = val_data["val_paths"]
    val_labels = val_data["val_labels"]

val_paths = [p.replace("\\", "/") for p in val_paths]

model.eval()

predictions = []
for path in val_paths:
    try:
        img = Image.open(path).convert("RGB")
        transformed = preprocess(img).unsqueeze(0).cuda()
        pred = torch.sigmoid(model(transformed)).item()
        predictions.append({"image_path": path, "pred": pred})
    except FileNotFoundError:
        print(f"Warning: Image not found at {path}. Skipping.")
    except Exception as e:
        print(f"Error processing image {path}: {e}. Skipping.")

with open('/content/val_predictions.json', 'w') as f:
    json.dump(predictions, f, indent=2)

labels_dict = {path: label for path, label in zip(val_paths, val_labels)}
with open('/content/val_labels.json', 'w') as f:
    json.dump(labels_dict, f)

metrics = score_from_files('/content/val_predictions.json', '/content/val_labels.json')

accuracy_str = f"{metrics['accuracy']:.3f}" if not np.isnan(metrics['accuracy']) else "N/A"
auc_str = f"{metrics['auc']:.3f}" if metrics['auc'] is not None else "N/A"

print(f"Accuracy: {accuracy_str}, AUC: {auc_str}")

false_positives = get_misclassified(metrics, kind="false_positive", top_n=3)
false_negatives = get_misclassified(metrics, kind="false_negative", top_n=3)

print("Most confident false positives (real images called fake):")
for r in false_positives:
    print(r)

print("\nMost confident false negatives (fake images called real):")
for r in false_negatives:
    print(r)

error_analysis_output = {
    "accuracy": accuracy_str,
    "auc": auc_str,
    "false_positives": false_positives,
    "false_negatives": false_negatives
}

with open('/content/error_analysis_final.json', 'w') as f:
    json.dump(error_analysis_output, f, indent=2)

files.download('/content/error_analysis_final.json')

results = {"false_positives": false_positives, "false_negatives": false_negatives}
with open('/content/misclassified_examples.json', 'w') as f:
    json.dump(results, f, indent=2)

files.download('/content/misclassified_examples.json')

model.load_state_dict(torch.load("/content/drive/MyDrive/model_plain.pt"))

import albumentations as A
from albumentations.pytorch import ToTensorV2

test_conditions = {
    "Clean": A.Compose([
        A.Resize(224, 224),
        A.Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711)),
        ToTensorV2()
    ]),
    "JPEG q30": A.Compose([
        A.Resize(224, 224),
        A.ImageCompression(quality_lower=30, quality_upper=30, p=1.0),
        A.Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711)),
        ToTensorV2()
    ]),
    "Blur σ=2": A.Compose([
        A.Resize(224, 224),
        A.GaussianBlur(sigma_limit=(2.0, 2.0), p=1.0),
        A.Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711)),
        ToTensorV2()
    ]),
    "Crop 80%": A.Compose([
        A.Resize(224, 224),
        A.RandomResizedCrop(height=224, width=224, scale=(0.8, 0.8), p=1.0),
        A.Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711)),
        ToTensorV2()
    ]),
}

import os
os.listdir('/content/Centaurus/aigc-detection3/eval')

import shutil
# FIXED: source path was missing the aigc-detection3 subfolder
shutil.copy('/content/Centaurus/aigc-detection3/scoring.py', '/content/Centaurus/aigc-detection3/eval/scoring.py')

import sys
sys.path.append('/content/Centaurus/aigc-detection3')
from eval.evaluate import evaluate

import numpy as np

def wrap_transform(transform):
    def wrapped(img):
        return transform(image=np.array(img))['image']
    return wrapped

test_conditions_wrapped = {name: wrap_transform(t) for name, t in test_conditions.items()}

model = FakeDetector(clip_model)
model.load_state_dict(torch.load("/content/drive/MyDrive/model_plain.pt"))
model = model.cuda().eval()

results_plain = {}
for name, transform in test_conditions_wrapped.items():
    val_dataset = ImageDataset(val_paths, val_labels, transform=transform)
    val_loader = DataLoader(val_dataset, batch_size=32)
    acc, auc = evaluate(model, val_loader)
    results_plain[name] = {"accuracy": round(acc*100, 2), "auc": round(auc, 4)}

print(results_plain)

with open('results_plain.json', 'w') as f:
    json.dump(results_plain, f, indent=2)

files.download('results_plain.json')

model = FakeDetector(clip_model)
model.load_state_dict(torch.load("/content/drive/MyDrive/model_augmented.pt"))
model = model.cuda().eval()

results_augmented = {}
for name, transform in test_conditions_wrapped.items():
    val_dataset = ImageDataset(val_paths, val_labels, transform=transform)
    val_loader = DataLoader(val_dataset, batch_size=32)
    acc, auc = evaluate(model, val_loader)
    results_augmented[name] = {"accuracy": round(acc*100, 2), "auc": round(auc, 4)}

print(results_augmented)

combined = {"plain": results_plain, "augmented": results_augmented}

with open('robustness_recheck.json', 'w') as f:
    json.dump(combined, f, indent=2)

files.download('robustness_recheck.json')

!pip freeze > requirements.txt
!wc -l requirements.txt